spring:
  # MariaDB
#  server
#  datasource:
#    url: jdbc:mariadb://maria_db:3306/projectdb?createDatabaseIfNotExist=true
#    username: root
#    password: root1234
#    driver-class-name: org.mariadb.jdbc.Driver

#  local
#  datasource:
#    url: jdbc:mariadb://localhost:3306/test?createDatabaseIfNotExist=true
#    username: root
#    password: root1234
#    driver-class-name: org.mariadb.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#      dialect: org.hibernate.dialect.MariaDBDialect

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: user1
    password: user1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /index.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match: "/api/v1/**"